# Load data

In [6]:
import numpy as np

from linear_classifiers import *
from prec_recall import prec_recall

In [7]:
option = "subsample"

if option == "subsample":
    X_train = np.load("../data/subsamp_data/processed_X_train.npy")
    X_val = np.load("../data/subsamp_data/processed_X_val.npy")
    X_test = np.load("../data/subsamp_data/processed_X_test.npy")
    y_train = np.load("../data/subsamp_data/processed_y_train.npy")
    y_val = np.load("../data/subsamp_data/processed_y_val.npy")
    y_test = np.load("../data/subsamp_data/processed_y_test.npy")

print("shape: {}".format(X_train.shape))
print(X_train)
print(X_train[0])

shape: (622, 28)
[[ 0.29015516  0.04924313 -0.74052367 ...  2.74526067 -0.2204016
   0.16823274]
 [-1.61218737 -4.62014787 -0.28331816 ...  0.89152121 -0.31278271
   0.26827516]
 [-4.28058383  1.42110001 -3.90822884 ... -1.14992267 -1.80988612
   0.72305143]
 ...
 [ 1.23220629  0.26485221  0.42781704 ... -0.44599829  0.03289931
   0.01365267]
 [ 1.20493424  3.23806951 -6.0103244  ...  0.05603474  0.49182782
   0.34084669]
 [-0.32479146  1.08346101 -1.20520689 ...  0.07256116  0.48961806
   0.33803559]]
[ 0.29015516  0.04924313 -0.74052367  2.86546277  1.39529392 -0.53516328
  0.14254337 -0.22276971 -1.46369065  1.71353755 -1.12757349 -0.70865735
  0.27218608  0.27471029  0.23519195 -0.46355271  0.47299539 -0.44789916
  1.79092415  0.24757953  0.33734885  1.01819058  0.30355001  0.83388612
 -1.2223061   2.74526067 -0.2204016   0.16823274]


# Neural Networks

In [3]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from prec_recall import prec_recall
# fix random seed for reproducibility
np.random.seed(7)

Using TensorFlow backend.
/Users/wenqi/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)


In [4]:
weights = []
biases = []

for i in range(1, 4):
    weights.append(np.load("../keras/models/w_{}.npy".format(i)))
    biases.append(np.load("../keras/models/b_{}.npy".format(i)))
    
for w in weights:
    print(w.shape)

(28, 12)
(12, 6)
(6, 1)


In [8]:
my_pred = neural_networks(X_val, weights, biases)
print(my_pred[0:10])
# print(my_pred)
prec_recall(y_val, my_pred)

[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]]
TP count:    92
FP count:    69
TN count:    25
FN count:    2
Precision rate:  0.5714285714285714
Recall rate: 0.9787234042553191


# Logistic Regression

In [9]:
w = np.load("../sklearn/model_LR/w.npy")
b = np.load("../sklearn/model_LR/b.npy")

my_pred = logistic_regression(X_val, w, b)
print(my_pred[0:10])
prec_recall(y_val, my_pred)

[1. 0. 1. 1. 1. 0. 1. 0. 1. 0.]
TP count:    92
FP count:    27
TN count:    67
FN count:    2
Precision rate:  0.773109243697479
Recall rate: 0.9787234042553191


# SVM

In [10]:
w = np.load("../sklearn/model_SVM/w.npy")
b = np.load("../sklearn/model_SVM/b.npy")

my_pred = logistic_regression(X_val, w, b)
print(my_pred[0:10])
prec_recall(y_val, my_pred)

[1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
TP count:    88
FP count:    6
TN count:    88
FN count:    6
Precision rate:  0.9361702127659575
Recall rate: 0.9361702127659575
